var annotated =
[
    [ "hb", null, [
      [ "detail", null, [
        [ "EventManager", "classhb_1_1detail_1_1EventManager.html", "classhb_1_1detail_1_1EventManager" ],
        [ "MessageManager", "classhb_1_1detail_1_1MessageManager.html", "classhb_1_1detail_1_1MessageManager" ],
        [ "traits", "structhb_1_1detail_1_1traits.html", null ],
        [ "traits< R(C::*)(A &) const  >", "structhb_1_1detail_1_1traits_3_01R_07C_1_1_5_08_07A_01_6_08_01const_01_01_4.html", "structhb_1_1detail_1_1traits_3_01R_07C_1_1_5_08_07A_01_6_08_01const_01_01_4" ],
        [ "traits< R(C::*)(const A &) const  >", "structhb_1_1detail_1_1traits_3_01R_07C_1_1_5_08_07const_01A_01_6_08_01const_01_01_4.html", "structhb_1_1detail_1_1traits_3_01R_07C_1_1_5_08_07const_01A_01_6_08_01const_01_01_4" ]
      ] ],
      [ "Box2DPlugin", "classhb_1_1Box2DPlugin.html", "classhb_1_1Box2DPlugin" ],
      [ "BoxCollider2d", "classhb_1_1BoxCollider2d.html", "classhb_1_1BoxCollider2d" ],
      [ "Camera", "classhb_1_1Camera.html", "classhb_1_1Camera" ],
      [ "CircleCollider2d", "classhb_1_1CircleCollider2d.html", "classhb_1_1CircleCollider2d" ],
      [ "ClickableComponent", "classhb_1_1ClickableComponent.html", "classhb_1_1ClickableComponent" ],
      [ "Clock", "classhb_1_1Clock.html", "classhb_1_1Clock" ],
      [ "Collider2d", "classhb_1_1Collider2d.html", "classhb_1_1Collider2d" ],
      [ "CollisionComponent", "classhb_1_1CollisionComponent.html", "classhb_1_1CollisionComponent" ],
      [ "Color", "structhb_1_1Color.html", "structhb_1_1Color" ],
      [ "ContactListener2d", "classhb_1_1ContactListener2d.html", "classhb_1_1ContactListener2d" ],
      [ "DataComponent", "classhb_1_1DataComponent.html", "classhb_1_1DataComponent" ],
      [ "DataComponent< T * >", "classhb_1_1DataComponent_3_01T_01_5_01_4.html", "classhb_1_1DataComponent_3_01T_01_5_01_4" ],
      [ "DataRepository", "classhb_1_1DataRepository.html", "classhb_1_1DataRepository" ],
      [ "EventManager", "classhb_1_1EventManager.html", "classhb_1_1EventManager" ],
      [ "Fixture2dData", "structhb_1_1Fixture2dData.html", "structhb_1_1Fixture2dData" ],
      [ "FunctionComponent", "classhb_1_1FunctionComponent.html", "classhb_1_1FunctionComponent" ],
      [ "Game", "classhb_1_1Game.html", "classhb_1_1Game" ],
      [ "GameObject", "classhb_1_1GameObject.html", "classhb_1_1GameObject" ],
      [ "InputManager", "classhb_1_1InputManager.html", "classhb_1_1InputManager" ],
      [ "JoyAxis", "structhb_1_1JoyAxis.html", "structhb_1_1JoyAxis" ],
      [ "JoyButtonPressed", "structhb_1_1JoyButtonPressed.html", "structhb_1_1JoyButtonPressed" ],
      [ "JoyButtonReleased", "structhb_1_1JoyButtonReleased.html", "structhb_1_1JoyButtonReleased" ],
      [ "KeyPressed", "structhb_1_1KeyPressed.html", "structhb_1_1KeyPressed" ],
      [ "KeyReleased", "structhb_1_1KeyReleased.html", "structhb_1_1KeyReleased" ],
      [ "ListenerComponent", "classhb_1_1ListenerComponent.html", "classhb_1_1ListenerComponent" ],
      [ "Material2d", "structhb_1_1Material2d.html", "structhb_1_1Material2d" ],
      [ "MessageManager", "classhb_1_1MessageManager.html", "classhb_1_1MessageManager" ],
      [ "MouseButtonWindow", "structhb_1_1MouseButtonWindow.html", "structhb_1_1MouseButtonWindow" ],
      [ "MouseButtonWorld", "structhb_1_1MouseButtonWorld.html", "structhb_1_1MouseButtonWorld" ],
      [ "Physics2d", "classhb_1_1Physics2d.html", "classhb_1_1Physics2d" ],
      [ "Plugin", "classhb_1_1Plugin.html", "classhb_1_1Plugin" ],
      [ "Rect", "classhb_1_1Rect.html", "classhb_1_1Rect" ],
      [ "Renderer", "classhb_1_1Renderer.html", "classhb_1_1Renderer" ],
      [ "Resource", "classhb_1_1Resource.html", "classhb_1_1Resource" ],
      [ "ResourceManager", "classhb_1_1ResourceManager.html", "classhb_1_1ResourceManager" ],
      [ "RigidBody2dComponent", "classhb_1_1RigidBody2dComponent.html", "classhb_1_1RigidBody2dComponent" ],
      [ "SFMLPlugin", "classhb_1_1SFMLPlugin.html", "classhb_1_1SFMLPlugin" ],
      [ "SoundBuffer", "classhb_1_1SoundBuffer.html", "classhb_1_1SoundBuffer" ],
      [ "SoundComponent", "classhb_1_1SoundComponent.html", "classhb_1_1SoundComponent" ],
      [ "SoundManager", "classhb_1_1SoundManager.html", "classhb_1_1SoundManager" ],
      [ "Sprite", "classhb_1_1Sprite.html", "classhb_1_1Sprite" ],
      [ "SpriteComponent", "classhb_1_1SpriteComponent.html", "classhb_1_1SpriteComponent" ],
      [ "Texture", "classhb_1_1Texture.html", "classhb_1_1Texture" ],
      [ "TextureManager", "classhb_1_1TextureManager.html", "classhb_1_1TextureManager" ],
      [ "Time", "classhb_1_1Time.html", "classhb_1_1Time" ],
      [ "TmxObjectTypeFactory", "classhb_1_1TmxObjectTypeFactory.html", "classhb_1_1TmxObjectTypeFactory" ],
      [ "TmxScene", "classhb_1_1TmxScene.html", "classhb_1_1TmxScene" ],
      [ "Transform", "classhb_1_1Transform.html", "classhb_1_1Transform" ],
      [ "Vector2d", "classhb_1_1Vector2d.html", "classhb_1_1Vector2d" ],
      [ "Vector3d", "classhb_1_1Vector3d.html", "classhb_1_1Vector3d" ],
      [ "WindowResized", "structhb_1_1WindowResized.html", "structhb_1_1WindowResized" ]
    ] ],
    [ "std", null, [
      [ "hash< pair< S, T > >", "structstd_1_1hash_3_01pair_3_01S_00_01T_01_4_01_4.html", "structstd_1_1hash_3_01pair_3_01S_00_01T_01_4_01_4" ]
    ] ]
];